source: src
destination: dist
theme: minima
lang: en
languages: ["en", "ru", "hy"]

title: Kanach Yerevan
description: Kanach Yerevan is a social movement that aims to make Yerevan a greener, more sustainable and more livable city.
author: Kanach Yerevan
email: makeyerevangreenagain@gmail.com

minima:
  date_format: "%d.%m.%Y"
  skin: solarized

instagram_username: kanach.yerevan
youtube_username: YerevanObserver

header_pages:
  - about.md
  - mapping.md
