# The URL the site will be built for
base_url = "https://myga.am"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "myga"
output_dir = "dist"
default_language = "en"

## Configure website languages.
[languages]

[languages.en]
title = "Kanach Yerevan"
build_search_index = true

[languages.ru]
title = "Kanach Yerevan"
build_search_index = true

[languages.ru.translations]
footer = "Kanach Yerevan это общественное движение, целью которого является сделать Ереван более зелёным, устойчивым и пригодным для жизни городом."
language_name = "Русский"
translation = "Перевод"

[languages.hy]
title = "Կանաչ Երևան"
build_search_index = true

[languages.hy.translations]
footer = "«Կանաչ Երևանը» հասարակական շարժում է, որի նպատակն է Երևանը դարձնել ավելի կանաչ, կայուն և բնակելի քաղաք։"
language_name = "Հայերեն"
translation = "Լեզուներ"

[translations]
footer = "Kanach Yerevan is a social movement that aims to make Yerevan a greener, more sustainable and more livable city."
language_name = "English"
translation = "Translation"
