name = "myga"
description = "An internal theme for Kanach Yerevan"
license = "MIT"
homepage = "https://github.com/KanachYerevan/kanachyerevan.github.io"
min_version = "0.1.0"
demo = "https://myga.am/"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
]

[author]
name = "Justin Forest"
homepage = "https://umonkey.net/"
